### ISSUE TITLE
Research on specific methods used in NLP Literature recommendation

### ISSUE THREAD

**Issue by farukcankaya** [TUM-IDP-WS-20/doc#9]
Parent: #1 
---
- [ ] Find general NLP techniques might be used for a recommendation(except topic modeling techniques. there is separate issue for it: [Research on Topic modeling techniques](https://github.com/TUM-IDP-WS-20/doc/issues/10))
- [ ] Collect practical examples and document

**Comment by farukcankaya** [comment]
https://www.quora.com/What-are-the-best-algorithms-for-building-recommender-systems
https://www.slideshare.net/CrossingMinds/recommendation-system-explained

**Comment by farukcankaya** [comment]
I'm not sure if there is a separate NLP technique apart from Topic modeling techniques. Because each dimensionality reduction technique is also counted as a topic modeling technique i.e. LSA. In essence [google](https://developers.google.com/machine-learning/recommendation/collaborative/matrix) categorized recommendation systems like:
- Content based filtering
- Collobrative filtering
- Deep neural networks

Techniques used in each category use some dimensionality reduction techniques to extract the embedding and they are counted as a topic modeling techniques. If not we can count some dimensionality reduction techniques such as PCA, SVD etc. as a technique apart from topic modeling techniques that are very popular nowadays:
- Latent Dirichlet Allocation (LDA)
- Non Negative Matrix Factorization (NMF)
- Parallel Latent Dirichlet Allocation (PLDA)
- Pachinko Allocation Model (PAM)

**Comment by farukcankaya** [comment]
@MelikeSila read many articles about recommendation systems. So, she may give an example for that otherwise we can close this task because we know that our focus will be on the **content-based topic modeling techniques**.

**Comment by MelikeSila** [comment]
- Used technique in paper 1 is "Multi-interest dataset recommendation (MIDR)" method used besides content-based dataset recommendation.
- Used method in paper 2 is "Model-based clustering, in which probabilistic parameters of a mixture model are estimated based on an EM (Expectation-Maximization) algorithm"

There are more papers to give an example but it is not necessary to share here it because we will use the topic modeling technique. On the other hand, the other used methods are solved particular problems so they may not help to solve out modeling problem. In the beginning, we will try topic modeling techniques.


Paper 1: "[A content-based dataset recommendation system for researchers—a case study on Gene Expression Omnibus (GEO) repository](https://academic.oup.com/database/advance-article/doi/10.1093/database/baaa064/5909105)"
Paper 2: "[PURE: A PUBMED ARTICLE RECOMMENDATION SYSTEM BASED ON CONTENT-BASED FILTERING](https://www.jstage.jst.go.jp/article/gi1990/18/0/18_0_267/_article/-char/ja/)"
